# indicating which version of Docker-compose we wish to use
version: "3.7"

services:
  flask-api-cluster:
    build: ./backend
    image: taskmaster_flask
    restart: always
    networks:
      - test
    container_name: tmflask
    ports:
      - "5000:5000"

  react-client: 
    build: ./nextjs-frontend 
    image: taskmaster_react
    restart: always
    networks:
      - test
    container_name: tmreact
    ports:
      - "3000:3000"

  web-server: 
    build: ./docker/nginx
    image: taskmaster_web
    restart: always
    networks:
      - test
    container_name: tmweb
    ports:
      - "80:8888"

  mysql-cluster: 
    build: ./docker/mysql
    image: taskmaster_db
    restart: always
    networks:
      - test
    container_name: tmdb
    ports:
      - "3306:3306"

networks:
  test:
    driver: bridge