---
apiVersion: v1
kind: Service
metadata:
  name: react-client
  # namespace: reactapp
  labels:
    web: reactclient
spec:
  type: NodePort
  selector:
    web: reactclient
  ports:
    - port: 8080
      nodePort: 30020
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  # namespace: reactapp
  labels:
    web: reactclient
spec:
  replicas: 1
  selector:
    matchLabels:
      web: reactclient
  template:
    metadata:
      name: client-pods
      # namespace: reactapp
      labels:
        web: reactclient
    spec:
      containers:
      - name: client-containers
        imagePullPolicy: Always
        image: 192.168.33.30:5000/taskmaster_react:latest
        ports:
          - name: tmreact-port
            containerPort: 8080
