---
apiVersion: v1
kind: Pod
metadata:
  name: taskmaster_db
  labels:
    app: taskmaster_db
spec:
  containers:
    - name: appcontainer
      image: taskmaster_db:lastest
      # volumeMounts:
      #   - mountPath: /var/lib/mysql
      #     name: dbvol
      ports:
        - name: taskmaster_db-port
          containerPort: 3306
  # volumes:
  #   - name: dbvol
  #     hostPath:
  #       path: /data
  #       type: Directory

---
apiVersion: v1
kind:  Service
metadata:
  name: taskmaster_db-service
spec:
  selector:
    app: taskmaster_db
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: taskmaster_db-port
