---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-cluster
  # namespace: reactapp
  labels:
    db: mysql
spec:
  selector:
    db: mysql
  ports:
    - port: 3306
      targetPort: 3306
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # namespace: reactapp
  labels:
    db: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      name: db-pods
      # namespace: reactapp
      labels:
        db: mysql
    spec:
      containers:
      - name: db-containers
        image: 192.168.33.30:5000/taskmaster_db:latest
        ports:
          - name: mysql-port
            containerPort: 3306
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-api-cluster
  # namespace: reactapp
  labels:
    backend: flaskapi
spec:
  selector:
    backend: flaskapi
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-api
  # namespace: reactapp
  labels:
    backend: flaskapi
spec:
  type: NodePort
  selector:
    backend: flaskapi
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  # namespace: reactapp
  labels:
    backend: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: flaskapi
  template:
    metadata:
      name: api-pods
      # namespace: reactapp
      labels:
        backend: flaskapi
    spec:
      containers:
      - name: db-containers
        image: 192.168.33.30:5000/taskmaster_flask:latest
        ports:
          - name: tmflask-port
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: react-client
  # namespace: reactapp
  labels:
    web: reactclient
spec:
  type: NodePort
  selector:
    web: reactclient
  ports:
    - port: 8080
      nodePort: 30020
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  # namespace: reactapp
  labels:
    web: reactclient
spec:
  replicas: 1
  selector:
    matchLabels:
      web: reactclient
  template:
    metadata:
      name: client-pods
      # namespace: reactapp
      labels:
        web: reactclient
    spec:
      containers:
      - name: client-containers
        image: 192.168.33.30:5000/taskmaster_react:latest
        ports:
          - name: tmreact-port
            containerPort: 8080
