---
apiVersion: v1
kind: Service
metadata: 
  name: flask-api-cluster
  # namespace: reactapp
  labels:
    backend: flaskapi
spec:
  selector:
    backend: flaskapi
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: flask-api
  # namespace: reactapp
  labels:
    backend: flaskapi
spec:
  type: NodePort
  selector:
    backend: flaskapi
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  # namespace: reactapp
  labels:
    backend: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      backend: flaskapi
  template:
    metadata:
      name: api-pods
      # namespace: reactapp
      labels:
        backend: flaskapi
    spec:
      containers:
      - name: db-containers
        imagePullPolicy: Always
        image: 192.168.33.30:5000/taskmaster_flask:latest
        ports:
          - name: tmflask-port
            containerPort: 5000