---
apiVersion: v1
kind: Pod
metadata:
  name: tmdb
  labels:
    app: taskmaster_db
spec:
  containers:
    - name: appcontainer
      image: 192.168.33.30:5000/taskmaster_db:latest
      # volumeMounts:
      #   - mountPath: /var/lib/mysql
      #     name: dbvol
      ports:
        - name: tmdb-port
          containerPort: 3306
  # volumes:
  #   - name: dbvol
  #     hostPath:
  #       path: /data
  #       type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: taskmasterdb-service
spec:
  selector:
    app: taskmaster_db
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: tmdb-port
