---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-cluster
  # namespace: reactapp
  labels:
    db: mysql
spec:
  selector:
    db: mysql
  ports:
    - port: 3306
      targetPort: 3306
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  # namespace: reactapp
  labels:
    db: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
  template:
    metadata:
      name: db-pods
      # namespace: reactapp
      labels:
        db: mysql
    spec:
      containers:
      - name: db-containers
        imagePullPolicy: Always
        image: 192.168.33.30:5000/taskmaster_db:latest
        ports:
          - name: mysql-port
            containerPort: 3306